### PR TITLE
Add support for looking up Private DNS Name for hostname

### PR DESCRIPTION
**Pull request by mekf**
In some circumstances - for example proxy settings that are configurable on hostnames - the `private_dns_name` is preferred over the `private_ip_address`

When `private_dns` is provided as the option in `.kitchen.yml`, the value of `private_dns_name` will be returned

```ruby
driver:
  interface: private_dns
```

When this option is unset, the `private_ip_address` will be returned as in the current implementation

### CODE REVIEW

**Comment by mekf** [comment]
\cc @zl4bv @tjnicholas

**Comment by jkeiser** [comment]
@mekf is the private dns name ever preferred over the private ip? Do we want to inject this third in the priority instead of fourth?

**Comment by zl4bv** [comment]
> is the private dns name ever preferred over the private ip?

Given a user is behind a proxy
And the user's no_proxy list is set to `.compute.internal` (because [IP prefixes are not supported](https://github.com/nahi/httpclient/blob/f60f6bad0a516b08052c5322eef21ffd9ff7ba08/lib/httpclient.rb#L527))
And the kitchen-ec2 instance is also behind the proxy
And the transport is set to WinRM

When kitchen-ec2 connects to the instance

Then it should connect to the instance using the private DNS address
And the WinRM requests should not go through the proxy

**Comment by jkeiser** [comment]
I'm unclear whether that is a more common or less common case than the opposite. Well, :+1: at any rate, seems reasonable.

**Comment by zl4bv** [comment]
The flipside is that the `compute.internal.` zone is generally only resolvable inside AWS. So a host outside of AWS would not be able connect to a test instance using private DNS even if the correct connectivity/routing was in place.

Certainly not sure which case is more common, but the "play it safe" option in my opinion would be to keep the current order with private IP address preferred over private DNS.

**Comment by jkeiser** [comment]
Fair enough! Paging @test-kitchen/maintainers @test-kitchen/kitchen-ec2-maintainers

**Comment by proffalken** [comment]
Code looks fine to me, approve of the ordering as well - I've had some real issues with Ansible when trying to SSH via private_dns so defaulting to the IP is the sensible thing to do IMHO.

+1

**Comment by mekf** [comment]
thanks @jkeiser @zl4bv

**Pull request merged**
