### PR TITLE
#394: Check subnet_filter as well when creating security group

### PR DESCRIPTION
**Pull request by llibicpep**

### CODE REVIEW

**Comment by multani** [comment]
@llibicpep Is there any way I can help in order to get this merged?

**Comment by llibicpep** [comment]
@multani I don't know how do I merge this :( I didn't heard back from project maintainers so far...

**Comment by multani** [comment]
@tas50 Is there anything I can do to help with this PR?

The behavior is similar to what can be find in [a similar (sort-of) tool](https://www.packer.io/docs/builders/amazon-ebs.html#vpc_id) and is simplifying the configuration of Kitchen by not having to specify a specific VPC ID and/or subnet ID - the, more generic, filter alone should be enough.

**Comment by avishayil** [comment]
Hi, I'd love to have this merged.

**Pull request merged**
