### PR TITLE
State file add ips mb

### PR DESCRIPTION
**Pull request by mbaitelman**
Add private and public IP's to the state file

### CODE REVIEW

**Comment by cheeseplus** [comment]
Why do we need this? We only need one IP to communicate to the instance and never is kitchen switching between the two. This is also breaking several tests so even if this was a feature we needed it can't be merged without fixing the tests.

**Comment by mbaitelman** [comment]
I found it useful to have the IP esp when debugging network issues in AWS.
I was going to spend some time to try to understand why those tests are failing.
If this is something that there isnt a community benefit for I will close the request.

**Comment by mbaitelman** [comment]
Closing the pull request as the use case is quite small.

**Comment by mbaitelman** [comment]
Learned some more things over the year. 
Turns out the [interface ](https://github.com/test-kitchen/kitchen-ec2#interface) value is what I needed.

**Pull request closed without merging**
