### PR TITLE
Lookup id from tag

### PR DESCRIPTION
**Pull request by dlukman**
Added feature which enables Subnet or Security Group ID lookup based on a Tag, if IDs are not provided.

### CODE REVIEW

**Comment by cheeseplus** [comment]
Looks like we're still getting a few failures but I like the feature.

**Comment by dlukman** [comment]
Great! I have added a new commit fixing the Rubocop issues that caused build failure.

**Comment by iiro** [comment]
+1

This is an excellent feature - would help to get rid of hard-coded ids...

**Comment by rveznaver** [comment]
Could someone review and merge this? It has been a while now :(

**Comment by jjasghar** [comment]
I feel like we should add some documentation before a merge here. These are the types of minor improvements can get overlooked if you don't document.

**Comment by cheeseplus** [comment]
If we can get an updated Readme or documentation on the feature somewhere I can +1 and get this merged this week.

**Comment by dlukman** [comment]
Readme updated. Anything else you need me to do?

**Comment by rveznaver** [comment]
pinging @cheeseplus

**Comment by rveznaver** [comment]
Bump?

**Pull request merged**
