### PR TITLE
Require Ruby 2.3 and aws-sdk-ec2

### PR DESCRIPTION
**Pull request by tas50**
Stop depending on the monolithic AWS sdk when we only need the ec2 SDK, which is tiny in comparison.

This is basically https://github.com/test-kitchen/kitchen-ec2/pull/339, but only with the aws / ruby change and w/o the various chefstyle updates.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by jesseadams** [comment]
@tas50 What is the status of this change?

**Comment by tas50** [comment]
We have the coordinate the change with inspec and chef provisioning aws. This part is ready when they are.

**Comment by jesseadams** [comment]
Is there anyway I can help push this along?

**Comment by jesseadams** [comment]
@tas50 Any chance we can get this coordinated soon? This keeps biting us!

**Comment by ChrisPetr0** [comment]
I agree, this is quite troublesome and time consuming to depend on all the gems in aws-sdk (v3) without the need for them.

**Comment by jtulick** [comment]
> I agree, this is quite troublesome and time consuming to depend on all the gems in aws-sdk (v3) without the need for them.

Same here, could we get an update on this?

**Comment by jesseadams** [comment]
@tas50 It's been 4 months. Is this going to get merged in soon or should we drop kitchen for testing and do something else?

**Comment by cheeseplus** [comment]
Test-kitchen has even less maintainers than it ever has, it's effectively a skeleton crew of part time folks at this point and they are trying their best to coordinate the upstream changes with the other products in ChefDK.

It's not on @tas50's shoulders and using a vague threat of dropping kitchen is bad form and isn't a great way to get help. Don't be that person.

**Comment by jeffbyrnes** [comment]
I appreciate @jesseadams’ frustration; they’ve been struggling with this for some time (and have comments strewn over multiple issues).

I’m going to take a peek at the other two repos & see if I can contribute while I’m still waiting to start a new gig next week; maybe I can move this along a little bit, or at least document what has to happen on those projects & create some clarity.

**Comment by jesseadams** [comment]
@cheeseplus I apologize if that came across as angry, offensive, or appeared as a threat. That was not my intention. I just need to know whats going on so we can plan accordingly. I know @tas50 is a busy guy, too.

@jeffbyrnes Please let me know if I can help in any way (testing, etc.). Thanks!

**Comment by tas50** [comment]
As many things go here this is actually much more complex than just this simple PR. We needed to make sure our entire ecosystem of tools in ChefDK / Workstation were on aws-sdk-v3 and doing that resulted in some pretty significant changes to some. For InSpec we first created a plugin system and broke out all AWS functionality into it's own plugin. That plugin is a ground up rewrite that uses the new SDK and a bunch of other core changes to InSpec. That work is wrapping up and that allows us to ship InSpec / kitchen-ec2 together in a major DK release this April that includes the v3 gem. It can't go in the current release because it's a major breaking change that may impact other uses in the current DK.

**Comment by jeffbyrnes** [comment]
Well! That is great news, in spite of the need for continued patience.

So it’s easier to jump off to the other relevant work, here’s all the issues & PRs I found that are involved in this:

* inspec/inspec#2571
    - This is probably the best one to keep an eye on; it seems to be the place for coordinating things
* inspec/train#350
* chef/chef-dk#1614
    - With this last one, it renders chef/chef-provisioning-aws#569 unnecessary (I think), since chef-provisioning is being dropped from ChefDK

**Comment by Zordrak** [comment]
`function clean_kitchen {
  kitchen ${@} 2> >(grep --color=always -v 'constant Struct::Tms is deprecated' >&2)
}`

**Pull request merged**
