### PR TITLE
add centos-6.5 amis

### PR DESCRIPTION
**Pull request by lamont-granquist**
from https://aws.amazon.com/marketplace/pp/B00IOYDTV6

### CODE REVIEW

**Comment by proffalken** [comment]
+1 - would be good to see this merged with #199

**Comment by cheeseplus** [comment]
Could this be rebased @lamont-granquist?

**Comment by jkeiser** [comment]
@lamont-granquist I believe this is obsoleted by #221, can you check if it works for your purpose now?

**Comment by lamont-granquist** [comment]
over a year old, i've completely forgotten my purpose...

**Pull request closed without merging**
