### PR TITLE
Creating windows-guest-support branch for kitchen-ec2

### PR DESCRIPTION
**Pull request by tyler-ball**
This tracks the changes in https://github.com/test-kitchen/test-kitchen/tree/windows-guest-support - when that is merged to master, this should be also.

These changes come from https://github.com/afiune/kitchen-ec2 .  I had to clean up some merge conflicts, so it will be slightly different.  Tests are also not going to pass yet - I need to clean up formatting, but it is in another branch for now since it makes the diff impossible to read.

\cc @afiune @fnichol @test-kitchen/windows 

NTS - merge afiune-transport-2 into this branch before going to master

### CODE REVIEW

**Comment by afiune** [comment]
@tyler-ball I think this might need some rebase.. but I like this!!! :+1:

**Comment by fnichol** [comment]
At the moment, this should work as a reference assuming it's too much work to re-integrate back in once #109 is merged. Hopefully a newer delta will be even shorter with improvements there and the Test Kitchen 1.4.0 codebase.

**Comment by tyler-ball** [comment]
@fnichol Correct, I am leaving this as reference, it will be re-implemented once I finish my work towards getting kitchen-ec2 1.4.0 ready

**Comment by sqorbrody** [comment]
:+1:

**Comment by tyler-ball** [comment]
Closing this as all the changes were merged in #150

**Pull request closed without merging**
