### PR TITLE
updated image_id and image_search blocks in README

### PR DESCRIPTION
**Pull request by kierandoonan**
Documentation updates to fix https://github.com/test-kitchen/kitchen-ec2/issues/236

### CODE REVIEW

**Comment by adamleff** [comment]
Thanks for the fix!  :+1:

**Comment by cheeseplus** [comment]
Missed this one but merged in #283

**Comment by pburkholder** [comment]
Oh, please merge this! This would have made my afternoon more delightful.

**Comment by pburkholder** [comment]
@cheeseplus Did you seriously just merge an open PR from March 9 simultaneous to my begging?

**Pull request closed without merging**
